allowBuilds:
  esbuild: true
engineStrict: true
saveTypes: true
autoDedupe: true
minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - yaml@1.10.3
  - "@sveltejs/adapter-auto@8.0.0"
  - "@sveltejs/adapter-static@4.0.0"
  - "@sveltejs/kit@3.0.0"
